/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi.database.client.khohang;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.WebRowSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import rmi.database.api.khohang.entity.SanPham;
import rmi.database.api.khohang.entity.SanPhamCuaHang;
import rmi.database.api.khohang.service.SanPhamCuaHangService;
import rmi.database.api.khohang.service.SanPhamService;

/**
 *
 * @author Sinh
 */
public class frmQuanLyKhoHang extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLyKhoHang
     */
    public frmQuanLyKhoHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHienThiTK = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        txtMaDanhMucSanPham = new javax.swing.JTextField();
        txtMauSac = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtChatLieu = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtDiaChiNhaSanXuat = new javax.swing.JTextField();
        txtTenNhaSanXuat = new javax.swing.JTextField();
        txtSoLuongNhap = new javax.swing.JTextField();
        txtSDTNhaSanXuat = new javax.swing.JTextField();
        txtTenSanPham = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHienThiSP = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtIdSanPham = new javax.swing.JTextField();
        txtMaSanPhamC = new javax.swing.JTextField();
        txtMaCuaHang = new javax.swing.JTextField();
        txtSoLuongCon = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbHienThiSP5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbHienThiHetHang = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        btnXoaC = new javax.swing.JButton();
        btnRefreshC = new javax.swing.JButton();
        btnThemC = new javax.swing.JButton();
        btnSuaC = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHienThiSPCQN = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHienThiSPCDN = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ KHO HÀNG");
        setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/purchase1.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(153, 102, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tình trạng sản phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tbHienThiTK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbHienThiTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên sản phẩm", "Tình trạng"
            }
        ));
        tbHienThiTK.setColumnSelectionAllowed(true);
        tbHienThiTK.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbHienThiTK);
        tbHienThiTK.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kiểm tra hàng trong kho", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 14))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 204));
        jLabel34.setText("Mã sản phẩm : ");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 204));
        jLabel35.setText("Mã DMSP :");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 204));
        jLabel36.setText("Tên sản phẩm :");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 204));
        jLabel37.setText("Địa chỉ nhà sản xuất :");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 204));
        jLabel38.setText("Chất liệu :");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 204));
        jLabel39.setText("Size :");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 204));
        jLabel40.setText("Màu sắc :");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 204));
        jLabel41.setText("Số lượng nhập :");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 204));
        jLabel42.setText("Tên nhà sản xuất :");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 204));
        jLabel43.setText("Giá nhập :");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 204));
        jLabel44.setText("SDT nhà sản xuất :");

        txtMaSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMaDanhMucSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMauSac.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtGiaNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtChatLieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtDiaChiNhaSanXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTenNhaSanXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSoLuongNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSDTNhaSanXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTenSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(668, 668, 668))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(42, 42, 42)
                                .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaDanhMucSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel43))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSDTNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaChiNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtMaDanhMucSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txtTenNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(txtDiaChiNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel44)
                    .addComponent(txtChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoabtnXoaActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reload.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshbtnRefreshActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThembtnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuabtnSuaActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reload.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportbtnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbHienThiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Mã danh mục sản phẩm", "Tên sản phẩm", "Chất liệu", "Size", "Màu", "Số lượng nhập", "Giá nhập", "Tên nhà sản xuất", "Địa chỉ nhà sản xuất", "SDT nhà sản xuất"
            }
        ));
        tbHienThiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHienThiSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHienThiSP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhập hàng về kho", jPanel2);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm chuyển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 14))); // NOI18N

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 204));
        jLabel45.setText("ID sản phẩm :");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 204));
        jLabel46.setText("Mã sản phẩm :");

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 204));
        jLabel49.setText("Giá bán :");

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 204));
        jLabel51.setText("Mã cửa hàng :");

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 204));
        jLabel54.setText("Số lượng còn :");

        txtIdSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdSanPham.setEnabled(false);

        txtMaSanPhamC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMaCuaHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSoLuongCon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtGiaBan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cửa hàng"));

        tbHienThiSP5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"QN", "Quy Nhơn"},
                {"DN", "Đà Nẵng"},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã cửa hàng", "Thông tin cửa hàng"
            }
        ));
        jScrollPane7.setViewportView(tbHienThiSP5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông báo nhập hàng"));

        tbHienThiHetHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm"
            }
        ));
        jScrollPane8.setViewportView(tbHienThiHetHang);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel54))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuongCon, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanPhamC, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtIdSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(txtMaSanPhamC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuongCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        btnXoaC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btnXoaC.setText("Xóa");
        btnXoaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCbtnXoaActionPerformed(evt);
            }
        });

        btnRefreshC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefreshC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reload.png"))); // NOI18N
        btnRefreshC.setText("Refresh");
        btnRefreshC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCbtnRefreshActionPerformed(evt);
            }
        });

        btnThemC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThemC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btnThemC.setText("Chuyển hàng về shop");
        btnThemC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCbtnThemActionPerformed(evt);
            }
        });

        btnSuaC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSuaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png"))); // NOI18N
        btnSuaC.setText("Sửa");
        btnSuaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCbtnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnThemC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(btnSuaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(btnXoaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(btnRefreshC, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaC)
                    .addComponent(btnSuaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemC))
                .addContainerGap())
        );

        tbHienThiSPCQN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Sản Phẩm", "Mã Sản Phẩm", "Mã cửa hàng", "Số lượng còn", "Giá bán"
            }
        ));
        tbHienThiSPCQN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHienThiSPCQNMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbHienThiSPCQN);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Cửa hàng Quy Nhơn", jPanel6);

        tbHienThiSPCDN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Sản Phẩm", "Mã Sản Phẩm", "Mã cửa hàng", "Số lượng còn", "Giá bán"
            }
        ));
        tbHienThiSPCDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHienThiSPCDNMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbHienThiSPCDN);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Cửa hàng Đà Nẵng", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chuyển hàng về shop", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien

            FileInputStream in = new FileInputStream("./src/rmi/database/client/khohang/config.txt");
            InputStreamReader isr = new InputStreamReader(in);
            BufferedReader br = new BufferedReader(isr);
            String[] tempIP = br.readLine().split(":");
            String[] tempPort = br.readLine().split(":");
            config.set(tempIP[1].trim(), tempPort[1].trim());

            SanPhamService sanPhamService = (SanPhamService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamService");
            UpdateSanPham(tbHienThiSP, sanPhamService.SanPham_GetByAll());
            UpdateSLSanPham(tbHienThiTK, sanPhamService.SanPham_GetByAll());
            

            SanPhamCuaHangService sanPhamCuaHangService = (SanPhamCuaHangService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamCuaHangService");
            UpdateSanPhamCuaHang(tbHienThiSPCQN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllQN());
            UpdateSanPhamCuaHang(tbHienThiSPCDN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllDN());
            UpdateYCNhapHang(tbHienThiHetHang, sanPhamCuaHangService.SanPhamCuaHangHet_GetByAll());

        } catch (Exception e) {
            DefaultTableModel model = (DefaultTableModel) tbHienThiSP.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            JOptionPane.showMessageDialog(this, "Lỗi kết nối. Vui lòng kiểm tra lại!!!!!!");
            frmConfig frmcf = new frmConfig();
            frmQuanLyKhoHang frmql = new frmQuanLyKhoHang();

            frmql = this;
            frmcf.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_formComponentShown

    private void btnXoabtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoabtnXoaActionPerformed
        if (txtMaSanPham.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã sản phẩm cần xóa");
        } else {

            try {
                SanPhamService sanPhamService = (SanPhamService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamService");

                String masp = txtMaSanPham.getText();

                sanPhamService.deleteSanPham(masp);
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien
                UpdateSanPham(tbHienThiSP, sanPhamService.SanPham_GetByAll());
            } catch (RemoteException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoabtnXoaActionPerformed

    private void btnRefreshbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshbtnRefreshActionPerformed
        txtMaSanPham.setText("");
        txtMaDanhMucSanPham.setText("");
        txtTenSanPham.setText("");
        txtChatLieu.setText("");
        txtGiaNhap.setText("");
        txtMauSac.setText("");
        txtSize.setText("");
        txtSDTNhaSanXuat.setText("");
        txtDiaChiNhaSanXuat.setText("");
        txtSoLuongNhap.setText("");
        txtTenNhaSanXuat.setText("");
        
        try {
            SanPhamService sanPhamService = (SanPhamService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamService");
            UpdateSanPham(tbHienThiSP, sanPhamService.SanPham_GetByAll());
            UpdateSLSanPham(tbHienThiTK, sanPhamService.SanPham_GetByAll());
            

            SanPhamCuaHangService sanPhamCuaHangService = (SanPhamCuaHangService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamCuaHangService");
            UpdateSanPhamCuaHang(tbHienThiSPCQN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllQN());
            UpdateSanPhamCuaHang(tbHienThiSPCDN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllDN());
            UpdateYCNhapHang(tbHienThiHetHang, sanPhamCuaHangService.SanPhamCuaHangHet_GetByAll());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnRefreshbtnRefreshActionPerformed

    private void btnThembtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThembtnThemActionPerformed
        if (checkNull()) {
            try {
                SanPhamService sanPhamService = (SanPhamService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamService");

                SanPham sanpham = new SanPham();
                sanpham.setMaSanPham(txtMaSanPham.getText());
                sanpham.setMaDanhMucSanpham(txtMaDanhMucSanPham.getText());
                sanpham.setTenSanPham(txtTenSanPham.getText());
                sanpham.setChatLieu(txtChatLieu.getText());
                sanpham.setSize(txtSize.getText());
                sanpham.setMau(txtMauSac.getText());
                sanpham.setSoLuongNhap(Integer.parseInt(txtSoLuongNhap.getText()));
                sanpham.setGiaNhap(Float.parseFloat(txtGiaNhap.getText()));
                sanpham.setTenNhaSanXuat(txtTenNhaSanXuat.getText());
                sanpham.setDiaChiNhaSanXuat(txtDiaChiNhaSanXuat.getText());
                sanpham.setSoDienThoaiNhaSanXuat(txtSDTNhaSanXuat.getText());

                sanPhamService.insertSanPham(sanpham);
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");

                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien
                UpdateSanPham(tbHienThiSP, sanPhamService.SanPham_GetByAll());
            } catch (RemoteException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | NotBoundException | MalformedURLException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThembtnThemActionPerformed

    private void btnSuabtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuabtnSuaActionPerformed
        if (checkNull()) {
            if (txtMaSanPham.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã sản phẩm cần sửa");
            }

            try {
                SanPhamService sanPhamService = (SanPhamService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamService");

                SanPham sanpham = new SanPham();
                sanpham.setMaSanPham(txtMaSanPham.getText());
                sanpham.setMaDanhMucSanpham(txtMaDanhMucSanPham.getText());
                sanpham.setTenSanPham(txtTenSanPham.getText());
                sanpham.setChatLieu(txtChatLieu.getText());
                sanpham.setSize(txtSize.getText());
                sanpham.setMau(txtMauSac.getText());
                sanpham.setSoLuongNhap(Integer.parseInt(txtSoLuongNhap.getText()));
                sanpham.setGiaNhap(Float.parseFloat(txtGiaNhap.getText()));
                sanpham.setTenNhaSanXuat(txtTenNhaSanXuat.getText());
                sanpham.setDiaChiNhaSanXuat(txtDiaChiNhaSanXuat.getText());
                sanpham.setSoDienThoaiNhaSanXuat(txtSDTNhaSanXuat.getText());

                sanPhamService.updateSanPham(sanpham);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");

                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien
                UpdateSanPham(tbHienThiSP, sanPhamService.SanPham_GetByAll());

            } catch (RemoteException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | NotBoundException | MalformedURLException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuabtnSuaActionPerformed

    private void btnExportbtnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportbtnExportActionPerformed
        exportExcel(tbHienThiSP);
    }//GEN-LAST:event_btnExportbtnExportActionPerformed

    private void tbHienThiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHienThiSPMouseClicked
        clickTable();
    }//GEN-LAST:event_tbHienThiSPMouseClicked

    private void btnXoaCbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCbtnXoaActionPerformed
        // TODO add your handling code here:
        if (txtIdSanPham.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sản phẩm cần xóa");
        } else {

            try {
                SanPhamCuaHangService sanPhamCuaHangService = (SanPhamCuaHangService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamCuaHangService");

                String idSanPham = txtIdSanPham.getText();

                sanPhamCuaHangService.deleteSanPhamCuaHang(idSanPham);
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien
                UpdateSanPhamCuaHang(tbHienThiSPCQN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllQN());
                UpdateSanPhamCuaHang(tbHienThiSPCDN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllDN());
            } catch (RemoteException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnXoaCbtnXoaActionPerformed

    private void btnRefreshCbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCbtnRefreshActionPerformed
        // TODO add your handling code here:
        txtIdSanPham.setText("");
        txtMaSanPhamC.setText("");
        txtMaCuaHang.setText("");
        txtSoLuongCon.setText("");
        txtGiaBan.setText("");

        try {
            SanPhamService sanPhamService = (SanPhamService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamService");
            UpdateSanPham(tbHienThiSP, sanPhamService.SanPham_GetByAll());
            UpdateSLSanPham(tbHienThiTK, sanPhamService.SanPham_GetByAll());
            

            SanPhamCuaHangService sanPhamCuaHangService = (SanPhamCuaHangService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamCuaHangService");
            UpdateSanPhamCuaHang(tbHienThiSPCQN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllQN());
            UpdateSanPhamCuaHang(tbHienThiSPCDN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllDN());
            UpdateYCNhapHang(tbHienThiHetHang, sanPhamCuaHangService.SanPhamCuaHangHet_GetByAll());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRefreshCbtnRefreshActionPerformed

    private void btnThemCbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCbtnThemActionPerformed
        if (checkNullChuyen()) {
            try {
                SanPhamCuaHangService sanPhamCuaHangService = (SanPhamCuaHangService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamCuaHangService");

                SanPhamCuaHang sanphamcuahang = new SanPhamCuaHang();
                sanphamcuahang.setIdSanPhamCuaHang(Integer.parseInt(txtIdSanPham.getText()));
                sanphamcuahang.setSoLuongCon(Integer.parseInt(txtSoLuongCon.getText()));
                sanphamcuahang.setGiaBan(Float.parseFloat(txtGiaBan.getText()));

                sanPhamCuaHangService.updateSanPhamCuaHang(sanphamcuahang);
                JOptionPane.showMessageDialog(rootPane, "Chuyển thành công");

                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien
                UpdateSanPhamCuaHang(tbHienThiSPCQN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllQN());
                UpdateSanPhamCuaHang(tbHienThiSPCDN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllDN());
            } catch (RemoteException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | NotBoundException | MalformedURLException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemCbtnThemActionPerformed

    private void btnSuaCbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCbtnSuaActionPerformed
        // TODO add your handling code here:
        if (checkNullChuyen()) {
            try {
                SanPhamCuaHangService sanPhamCuaHangService = (SanPhamCuaHangService) Naming.lookup("rmi://" + config.ServerIP.trim() + ":" + config.ServerPort + "/SanPhamCuaHangService");

                SanPhamCuaHang sanphamcuahang = new SanPhamCuaHang();
                sanphamcuahang.setIdSanPhamCuaHang(Integer.parseInt(txtIdSanPham.getText()));
                sanphamcuahang.setSoLuongCon(Integer.parseInt(txtSoLuongCon.getText()));
                sanphamcuahang.setGiaBan(Float.parseFloat(txtGiaBan.getText()));

                sanPhamCuaHangService.updateSanPhamCuaHang(sanphamcuahang);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");

                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");//set giao dien
                UpdateSanPhamCuaHang(tbHienThiSPCQN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllQN());
                UpdateSanPhamCuaHang(tbHienThiSPCDN, sanPhamCuaHangService.SanPhamCuaHang_GetByAllDN());
            } catch (RemoteException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | NotBoundException | MalformedURLException ex) {
                Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuaCbtnSuaActionPerformed

    private void tbHienThiSPCQNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHienThiSPCQNMouseClicked
        clickTableChuyen();
    }//GEN-LAST:event_tbHienThiSPCQNMouseClicked

    private void tbHienThiSPCDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHienThiSPCDNMouseClicked
        // TODO add your handling code here:
        clickTableChuyen();
    }//GEN-LAST:event_tbHienThiSPCDNMouseClicked
    private boolean checkNull() {
        String errorMessage = "";
        if (txtMaSanPham.getText().isEmpty() || txtChatLieu.getText().isEmpty()
                || txtDiaChiNhaSanXuat.getText().isEmpty()
                || txtMaDanhMucSanPham.getText().isEmpty() || txtMauSac.getText().isEmpty()
                || txtSDTNhaSanXuat.getText().isEmpty() || txtSize.getText().isEmpty()
                || txtTenNhaSanXuat.getText().isEmpty() || txtTenSanPham.getText().isEmpty()) {
            errorMessage += "Vui lòng nhập đầy đủ thông tin\n";
        }

        if (!isNumeric(txtSoLuongNhap.getText()) || !isNumeric(txtGiaNhap.getText())) {
            errorMessage += "Số lượng nhập & giá nhập phải là số";
        }

        if (errorMessage.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, errorMessage);
            return false;
        }
    }

    private boolean checkNullChuyen() {
        String errorMessage = "";
        if (txtMaSanPhamC.getText().isEmpty() || txtMaCuaHang.getText().isEmpty()) {
            errorMessage += "Vui lòng nhập đầy đủ thông tin\n";
        }

        if (!isNumeric(txtGiaBan.getText()) || !isNumeric(txtSoLuongCon.getText())) {
            errorMessage += "Số lượng còn & giá bán phải là số";
        }

        if (errorMessage.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, errorMessage);
            return false;
        }
    }

    public boolean isNumeric(String maybeNumeric) {
        return maybeNumeric != null && maybeNumeric.matches("[0-9]+");
    }

    private void UpdateSanPham(JTable jtbDanhSachDV, WebRowSet wrs) {
        try {
            DefaultTableModel dfTable = (DefaultTableModel) jtbDanhSachDV.getModel();
            dfTable.getDataVector().removeAllElements();
            Vector rowData;

            while (wrs.next()) {
                rowData = new Vector();
                rowData.add(wrs.getString("ma_sanpham"));
                rowData.add(wrs.getString("ma_danhmucsanpham"));
                rowData.add(wrs.getString("ten_sanpham"));
                rowData.add(wrs.getString("chatlieu"));
                rowData.add(wrs.getString("size"));
                rowData.add(wrs.getString("mau"));
                rowData.add(wrs.getInt("soluongnhap"));
                rowData.add(wrs.getDouble("gianhap"));
                rowData.add(wrs.getString("tennhasanxuat"));
                rowData.add(wrs.getString("diachinhasanxuat"));
                rowData.add(wrs.getString("sdtnhasanxuat"));

                dfTable.addRow(rowData);
            }
            jtbDanhSachDV.setModel(dfTable);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void UpdateSLSanPham(JTable jtbDanhSachDV, WebRowSet wrs) {
        try {
            DefaultTableModel dfTable = (DefaultTableModel) jtbDanhSachDV.getModel();
            dfTable.getDataVector().removeAllElements();
            Vector rowData;

            while (wrs.next()) {
                rowData = new Vector();
                rowData.add(wrs.getString("ten_sanpham"));
                rowData.add(wrs.getInt("soluongnhap"));

                dfTable.addRow(rowData);
            }
            jtbDanhSachDV.setModel(dfTable);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void exportExcel(JTable table) {

        try {
            String filename = "CSDLKH.xls";
            String workingDirectory = System.getProperty("user.dir");

            String absoluteFilePath = "";

            absoluteFilePath = workingDirectory + File.separator + filename;

            System.out.println("Đường dẫn file : " + absoluteFilePath);

            File file = new File(absoluteFilePath);
            if (file.createNewFile()) {
                JOptionPane.showMessageDialog(null, "Tạo file thành công!");

            } else {
                JOptionPane.showMessageDialog(null, "Tạo file thành công!");
            }

            FileWriter out = new FileWriter(file);
            BufferedWriter bwrite = new BufferedWriter(out);
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            // ten Cot
            for (int j = 0; j < table.getColumnCount(); j++) {
                bwrite.write(model.getColumnName(j) + "\t");
            }
            bwrite.write("\n");
            // Lay du lieu dong
            for (int j = 0; j < table.getRowCount(); j++) {
                for (int k = 0; k < table.getColumnCount(); k++) {
                    bwrite.write(model.getValueAt(j, k) + "\t");
                }
                bwrite.write("\n");
            }
            bwrite.close();
            JOptionPane.showMessageDialog(null, "Lưu file thành công!");
        } catch (Exception e2) {
            JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
        }
    }

    private void UpdateSanPhamCuaHang(JTable jtbDanhSachDV, WebRowSet wrs) {
        try {
            DefaultTableModel dfTable = (DefaultTableModel) jtbDanhSachDV.getModel();
            dfTable.getDataVector().removeAllElements();
            Vector rowData;

            while (wrs.next()) {
                rowData = new Vector();
                rowData.add(wrs.getInt("id_sanphamcuahang"));
                rowData.add(wrs.getString("ma_sanpham"));
                rowData.add(wrs.getString("ma_cuahang"));
                rowData.add(wrs.getInt("soluongcon"));
                rowData.add(wrs.getFloat("giaban"));

                dfTable.addRow(rowData);
            }
            jtbDanhSachDV.setModel(dfTable);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void UpdateYCNhapHang(JTable jtbDanhSachDV, WebRowSet wrs) {
        try {
            DefaultTableModel dfTable = (DefaultTableModel) jtbDanhSachDV.getModel();
            dfTable.getDataVector().removeAllElements();
            Vector rowData;

            while (wrs.next()) {
                rowData = new Vector();
                rowData.add(wrs.getString("ma_sanpham"));
                rowData.add(wrs.getString("ma_cuahang"));

                dfTable.addRow(rowData);
            }
            jtbDanhSachDV.setModel(dfTable);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void clickTable() {
        int Row = tbHienThiSP.getSelectedRow();
        txtMaSanPham.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 0)));
        txtMaDanhMucSanPham.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 1)));
        txtTenSanPham.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 2)));
        txtChatLieu.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 3)));
        txtSize.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 4)));
        txtMauSac.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 5)));
        txtSoLuongNhap.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 6)));
        txtGiaNhap.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 7)));
        txtTenNhaSanXuat.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 8)));
        txtDiaChiNhaSanXuat.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 9)));
        txtSDTNhaSanXuat.setText(String.valueOf(tbHienThiSP.getValueAt(Row, 10)));
    }

    public void clickTableChuyen() {
        int Row = tbHienThiSPCQN.getSelectedRow();
        txtIdSanPham.setText(String.valueOf(tbHienThiSPCQN.getValueAt(Row, 0)));
        txtMaSanPhamC.setText(String.valueOf(tbHienThiSPCQN.getValueAt(Row, 1)));
        txtMaCuaHang.setText(String.valueOf(tbHienThiSPCQN.getValueAt(Row, 2)));
        txtSoLuongCon.setText(String.valueOf(tbHienThiSPCQN.getValueAt(Row, 3)));
        txtGiaBan.setText(String.valueOf(tbHienThiSPCQN.getValueAt(Row, 4)));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLyKhoHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshC;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaC;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemC;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbHienThiHetHang;
    private javax.swing.JTable tbHienThiSP;
    private javax.swing.JTable tbHienThiSP5;
    private javax.swing.JTable tbHienThiSPCDN;
    private javax.swing.JTable tbHienThiSPCQN;
    private javax.swing.JTable tbHienThiTK;
    private javax.swing.JTextField txtChatLieu;
    private javax.swing.JTextField txtDiaChiNhaSanXuat;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtIdSanPham;
    private javax.swing.JTextField txtMaCuaHang;
    private javax.swing.JTextField txtMaDanhMucSanPham;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtMaSanPhamC;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtSDTNhaSanXuat;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtSoLuongCon;
    private javax.swing.JTextField txtSoLuongNhap;
    private javax.swing.JTextField txtTenNhaSanXuat;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables

}
